#!/bin/bash

read -p "Enter a valid remote email account to which QMT will send mail: " ruser
if [ -z "$ruser" ]
then
   echo "No remote user entered, exiting..."
   exit 1
fi

user=postmaster
host=`hostname -I`

DOMAINS=/home/vpopmail/domains
user=postmaster
DOMAINS=/home/vpopmail/domains

for domain in `ls $DOMAINS`
do
   pass=`/home/vpopmail/bin/vuserinfo $user@$domain | grep "clear passwd: " | sed 's/clear passwd: //'`
done
if [ -z "$domain" ]
then
   echo "No domain..."
   exit 1
fi

# If special characters are in username or password curl will fail unless they're replaced
opass=$pass

spl=('%' '#' '$' '!' '&' "'" '(' ')' '*' '+' ',' '/' ':' ';' '=' '?' '@' '[' ']')
rep=('%24' '%23' '%21' '%25' '%26' '%27' '%28' '%29' '%2A' '%2B' '%2C' '%2F' '%3A' '%3B' '%3D' '%3F' '%40' '%5B' '%5D')

for i in "${!spl[@]}"; do
   if [[ "$pass" == *"${spl[$i]}"* ]]; then
       pass=${pass//${spl[$i]}/${rep[$i]}}
   fi
   if [[ "$user" == *"${spl[$i]}"* ]]; then
       user=${user//${spl[$i]}/${rep[$i]}}
   fi
done


#bash -c 'echo a login '"$user@$domain $pass"'; while read x; do echo "$x"; done' | openssl s_client -crlf -connect  localhost:993

curl -v --insecure -I imaps://${user}%40${domain}:${pass}@$host &> ./xxx
yyy=`cat ./xxx | grep "OK Logged in"`
if [[ ! -z $yyy ]]
then
   echo -n "IMAPS: $user@$domain --> " && tput setaf 2 && echo "success" && tput sgr0
else
   echo -n "IMAPS: $user@$domain --> " && tput setaf 1 && echo "failure" && tput sgr0
fi

pass=$opass

dswak=/usr/local/bin
[ ! -f $dswak/swaks ] && wget -P $dswak http://www.jetmore.org/john/code/swaks/latest/swaks &> /dev/null && chown root.root $dswak/swaks && chmod +x $dswak/swaks
swaks --to $ruser --from $user@$domain --server $host --port 587 --ehlo test -tls --auth login --auth-user $user@$domain --auth-password $pass &> ./xxx
yyy=`cat xxx | grep "250 ok "`
if [[ ! -z $yyy ]]
then
   echo -n "Submission: $user@$domain --> " && tput setaf 2 && echo "success" && tput sgr0
else
   echo -n "Submission: $user@$domain --> " && tput setaf 1 && echo "failure" && tput sgr0
fi
rm -f ./xxx
swaks --to $ruser --from $user@$domain --server $host --port 465 --ehlo test -tlsc --auth login --auth-user $user@$domain --auth-password $pass &> ./xxx
yyy=`cat xxx | grep "250 ok "`
if [[ ! -z $yyy ]]
then
   echo -n "SMTPS: $user@$domain --> " && tput setaf 2 && echo "success" && tput sgr0
else
   echo -n "SMTPS: $user@$domain --> " && tput setaf 1 && echo "failure" && tput sgr0
fi
rm -f ./xxx
